<div class="row">
    <p>I am an expat from Boston, England, currently living in dtc with my fiancee Alana, a bearded dragon, and a 
    tabby cat named Primma. I'm a senior software engineer particularly skilled with LAMP. In my free time, 
    I am an avid chess player, a golfer, and a gnome Death Knight.</p>

    <p>Feel free to contact me <a href="/contact/index">here</a></p>
</div>

<div class="row col-md-12">
    <img style="margin-left:auto;margin-right:auto;" src="/files/deanandalana.jpg" alt="" title="" />
</div>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#aboutNav").attr("class", "active"); 
    }, 0);
});
</script>