<h3>Below is a list of the current RSVP's and their status.</h3>
<a href="/rsvp/add">Add an RSVP</a>

<?php
echo $this->partial('zfc-datagrid/renderer/bootstrapTable/layout', 
                    $this->viewModel()->getCurrent()->getVariables()); 
?>
<style>
table thead tr + tr{
    display:none;
}
</style>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#rsvpNav").attr("class", "active"); 
    }, 0);
});
</script>