<script type="text/javascript" src="http://chesstempo.com/js/pgnyui.js"></script>
<script type="text/javascript" src="http://chesstempo.com/js/pgnviewer.js"></script>  
<link type="text/css" rel="stylesheet" href="http://chesstempo.com/css/board-min.css"></link> 

<table width="100%">
    <tr><th>White</th><th>Black</th><th>Date</th><th>Site</th><th>Result</th><th>Play</th>
    <?php
    $count = 1;
    foreach($this->games as $model){
        print '<tr>';
        print '<td>'.$model->getWhitePlayer().' ('.$model->getWhiteRating().')</td>';
        print '<td>'.$model->getBlackPlayer().' ('.$model->getBlackRating().')</td>';
        print '<td>'.$model->getDate().'</td>';
        print '<td>'.$model->getSite().'</td>';
        print '<td>'.$model->getResult().'</td>';
        //print '<td><a href="/chessgames/edit/'.$model->getId().'">Edit</a></td>';
        print '<td><a href="/chessgames/show/'.$model->getId().'">Play</a></td>';
        print '</tr>';
    }
    ?>
</table>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#chessNav").attr("class", "active"); 
    }, 0);
});
</script>