<script type="text/javascript" src="http://chesstempo.com/js/pgnyui.js"></script>
<script type="text/javascript" src="http://chesstempo.com/js/pgnviewer.js"></script>  
<link type="text/css" rel="stylesheet" href="http://chesstempo.com/css/board-min.css"></link> 
<div class="row">
    <a href="http://www.uschess.org/assets/msa_joomla/MbrDtlMain.php?14819401" target="_blank">Click here to view my current USCF information</a>
</div>
<div class="row" style="margin-top:15px;">
    <strong><u>Current Published Rating</u></strong><br />
    <p>
        Regular Rating: 2005<br />
        Quick Rating:&nbsp;&nbsp;&nbsp;&nbsp;1878<br />
        Blitz Rating:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1936
    </p>
</div>
<?php
echo $this->partial('zfc-datagrid/renderer/bootstrapTable/layout', 
                    $this->viewModel()->getCurrent()->getVariables()); 
?>
<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#chessNav").attr("class", "active"); 
    }, 0);
});
</script>
<style>
    table tr:FIRST-CHILD + tr
{
    display:none;
}
</style>