<script type="text/javascript" src="http://chesstempo.com/js/pgnyui.js"></script>
<script type="text/javascript" src="http://chesstempo.com/js/pgnviewer.js"></script>  
<link type="text/css" rel="stylesheet" href="http://chesstempo.com/css/board-min.css"></link> 

<table width="100%">
    <tr><th>White</th><th>Black</th><th>Date</th><th>Site</th>
    <?php
    $count = 1;
    foreach($this->games as $model){
        print '<tr>';
        print '<td>'.$model->getWhitePlayer().' ('.$model->getWhiteRating().')</td>';
        print '<td>'.$model->getBlackPlayer().' ('.$model->getBlackRating().')</td>';
        print '<td>'.$model->getDate().'</td>';
        print '<td>'.$model->getSite().'</td>';
        print '</tr>';
        print '<tr>';
        print '<td colspan="3"><div id="chessgame_'.$count.'-container"></div></td>';
        print '<td><div id="chessgame_'.$count.'-moves"></div> </td>';
        print '</tr>';
        
        print '<script>  
                new PgnViewer(  
                  { boardName: "chessgame_'.$count.'",  
                    pgnFile: \''.$model->getPgnString().'\',  
                    pieceSet: \'leipzig\',   
                    pieceSize: 46  
                  }  
                );  
                </script>';
        $count++;
    }
    ?>
</table>