<div class="col-sm-6 col-md-6">
    <img class="col-sm-12 col-md-12" src="/weddingpics/belize.png" alt="" title="" />
</div>
<div class="col-sm-6 col-md-6">
    <p>If you are interested in giving Alana and Dean a gift, they have planned an adventurous honeymoon in Belize, complete with scuba-diving, caving, exploring Mayan ruins, and bushwhacking through the rainforest.</p>
    <p>Any donations to this fund would be greatly appreciated.</p>
</div>


<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#registryNav").attr("class", "active"); 
    }, 0);
});
</script>