<div class="col-sm-6 col-md-6">
    <img class="col-sm-12 col-md-12" src="/weddingpics/belize.png" alt="" title="" />
</div>
<div class="col-sm-6 col-md-6">
    <p>We have planned an adventurous honeymoon in Belize, complete with scuba-diving, caving, exploring Mayan ruins, and bushwhacking through the rainforest.</p>
    <p>It would mean so much to us if you would help us have this adventure.</p>
    <hr />
    <h4 style="font-family:Trebuchet MS;">Offline:</h4>
    <p>Dean Clow<br />
    9959 E Peakview Ave. S204<br />
    Englewood, CO 80111</p>
    <hr />
    <h4 style="font-family:Trebuchet MS;">Via Paypal:</h4>
    <form action="https://www.paypal.com/cgi-bin/webscr" target="_blank" method="post">
      <input type="hidden" name="cmd" value="_donations" />
      <input type="hidden" name="business" value="deanrclow@gmail.com" />
      <input type="hidden" name="undefined_quantity" value="1" />
      <input type="hidden" name="item_name" value="Alana &amp; Dean's Wedding Registry" />
      <input type="hidden" name="item_number" value="1" />
      <input type="hidden" name="shipping" value="0.00" />
      <input type="hidden" name="no_shipping" value="1" />
      <input type="hidden" name="currency_code" value="USD" />
      <input type="hidden" name="lc" value="US" />
      <input type="hidden" name="return" value="http://deanclow.com/registry/thank-you" />
        <fieldset>
            <input type="hidden" name="submitted" value="1" />
            <div class="row" style="margin-top:10px;">
                <div class="col-sm-5 col-md-5">
                    <span style="color:red;">*</span> <label style="font-family:Trebuchet MS;" for="cn">Name &amp; Comments</label>
                </div>
                <div class="col-sm-7 col-md-7">
                    <textarea name="cn" id="cn" class="col-sm-12 col-md-12" rows="8" required></textarea>
                </div>
            </div>
            <div class="row" style="margin-top:10px;">
                <div class="col-sm-5 col-md-5">
                    <span style="color:red;">*</span> <label style="font-family:Trebuchet MS;" for="amount">Amount</label>
                </div>
                <div class="col-sm-7 col-md-7">
                    $<input type="text" name="amount" id="amount" style="width:80px;" value="0.00" />
                </div>
            </div>
            <div class="row" style="margin-top:10px;">
                <div class="col-md-offset-4">
                    <input class="btn btn-lg btn-orange" style="background-color:#738965;border-bottom:2px solid #738965" type="submit" value="Send Gift" />
                </div>
            </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#registryNav").attr("class", "active"); 
    }, 0);
});
</script>
<style>
    h4{
        font-weight:bold;
    }
    label{
        font-weight:normal;
    }
</style>