<p style="width:100%;text-align:center;"><img style="width:285px;height:120px;" src="/weddingpics/background.png" /></p>
<h2 style="text-align:center;">Thank you so much for your gift!</h2>
<p style="text-align:center;">We will be thinking of you when we are rappelling into Actun Loch Tunich sink hole.</p>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#registryNav").attr("class", "active"); 
    }, 0);
});
</script>