<link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.3/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.3/fotorama.js"></script> <!-- 16 KB -->
<div class="col-sm-6 col-md-6">
    <div class="fotorama"
         data-arrows="true"
         data-click="true"
         data-swipe="false"
         data-nav="thumbs"
         data-autoplay="true"
         data-stopautoplayontouch="true"
         data-transition="dissolve"
         data-width="100%"
         data-ratio="1024/768">
      <img src="/weddingpics/1.png">
      <img src="/weddingpics/2.png">
      <img src="/weddingpics/3.png">
      <img src="/weddingpics/4.png">
      <img src="/weddingpics/7.png">
      <img src="/weddingpics/8.png">
      <img src="/weddingpics/9.png">
      <img src="/weddingpics/10.png">
    </div>
</div>
<div class="col-sm-6 col-md-6" style="text-align:center;">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p style="width:100%;text-align:center;"><img src="/weddingpics/background.png" /></p>
    <p style="font-family:Georgia;font-size:30px;">Alana &amp; Dean</p>
    <p>&nbsp;</p>
    <p>September 12, 2015, 5:00pm</p>
    <p>at the Thomas family home in Morrison, CO</p>
    <p>Reception to follow</p>
    <p>&nbsp;</p>
    <p style="font-size:12px;"><i>The ceremony and reception will take place outdoors,<br />so please dress accordingly.</i></p>
</div>

<style>
    body{
        background:#f6f6f6;
    }
    .georgiaFont{
        font-family:Georgia, serif;
    }
    .fotorama{
        margin-top:40px;
    }
    @media only screen 
    and (min-device-width : 768px) 
    and (max-device-width : 1024px) {
        .fotorama{
            margin-top:90px;
        }
    }
</style>