<script type="text/javascript">
$(document).ready(function() {
    /*setTimeout(function(){
       $(".nav li").removeClass("");  
       $("#resumeNav").attr("class", "active"); 
    }, 0);*/
});
</script>

<h1 style="text-align:center;">DEAN CLOW</h1>

<p>Full stack software engineer with special expertise in APIs and web services.<br />
    Comfortable implementing great user experiences and designing database schemas. <br />
    Experienced with building distributed systems and using REST/SOAP web APIs. Product focused and deeply passionate about solving interesting problems. Open-source contributor.</p>

<h2 style="border-bottom:1px solid #000;">SKILLS</h2>
<ul>
    <li>Web application development</li>
    <li>Web APIs/services</li>
    <li>Zend Framework 2</li>
    <li>CakePHP</li>
    <li>MySQL</li>
    <li>JQuery</li>
    <li>Agile Development</li>
    <li>Continuous Integration</li>
    <li>Big data</li>
</ul>

<h2 style="border-bottom:1px solid #000;">EMPLOYMENT</h2>
<p>Senior Software Engineer                 Educational Measures                                  Summer 2006 – Winter 2014</p>
<p style="font-weight:bold;">Projects</p>
<ul>
    <li><strong>Audience Response System</strong> (2011 – 2014). Distributed system that utilizes mobile devices to display and collect data. Agile, LAMP, NodeJS, JQuery, TomCat. Based on Zend2 Framework.</li>
    <li><strong>Outcomes Analysis Reporting</strong> (2006 - 2014). Reporting engine for analyzing data and producing dynamic reports based on data collected from continuing medical education seminars. LAMP, XML, SOAP, Prototype JS, TomCat. In-house framework.</li>
    <li><strong>Grant Management</strong> (2006 - 2014). Web application that analyzes medical grant lifecycle and beneficiary information. LAMP, JavaScript, JQuery. In-house framework.</li>
    <li><strong>Learning Management System</strong> (2012 – 2013). Web application that delivers online coursework in continuing medical education. LAMP, XML, JavaScript, JQuery. In-house framework.</li>
    <li><strong>Performance Improvement Measure</strong> (2010 - 2013). Web application to measure self-assessments of performance before and after educational interventions. LAMP, JavaScript, JQuery. In-house framework.</li>
    <li><strong>Kiosk Data Collection</strong> (2012). Localized Web survey to gather continuing medical education outcomes information. LAMP, JavaScript, JQuery. In-house framework.</li>
    <li><strong>Accreditation Guidance</strong> (2009). Web application to guide clients through the process of continuing medical education accreditation, including report production. LAMP, XML, JSON, JQuery. In-house framework.</li>
    <li><strong>Douglas County Public Schools Application</strong> (2012 – 2013). Created an API and interface for inputting and distributing information to mobile applications on Android and Apple devices. Includes integration with Google, Facebook, Twitter, and RSS feeds. LAMP, XML, SOAP, JavaScript, JQuery.  In-house framework.</li>
    <li><strong>Content Management System</strong> (2011 – 2014). Content management system able to create custom sites using shared codebase and widgets to provide rich media interaction. LAMP, JavaScript, JQuery. In-house framework.</li>
</ul>

<h2 style="border-bottom:1px solid #000;">EDUCATION</h2>
<p>Boston, England                     University of Sunderland                                  Fall 2001 – Winter 2005</p>
<ul>
    <li>Bachelor's Degree in Computing (w/Honors).</li>
</ul>

<h2 style="border-bottom:1px solid #000;">ADDITIONAL EXPERIENCE AND AWARDS</h2>
<ul>
    <li>Attended ZendCon 2014, Silicon Valley</li>
    <li>Received Colorado School Public Relations Association (COSPRA) Golden Achievement Award for the Douglas County Public Schools application</li>
    <li>Open-source contributor</li>
</ul>

<h2 style="border-bottom:1px solid #000;">LANGUAGES AND TECHNOLOGIES</h2>
<ul>
    <li>PHP; MySQL; Java; Android; JavaScript; JQuery; NodeJS; JSON; XML (XSD) Schema;</li>
    <li>Zend Studio;PHPStorm;Eclipse;Zend2 Framework; Linux; Git; SVN; Crucible; Jenkins; PHPUnit; LeanKit; QuickBase; REST; Apigility; Continuous Integration; Database Migration;</li>
</ul>