<p>When Cameron Naish told Alana that he had a single coworker with an English accent, she knew she had to meet him. Dean and Alana chatted on Facebook for three days before hitting it off on a spur-of-the-moment date at a local bar.</p>
<p>The two years leading up to their engagement were full of adventure - snowmobiling, hiking, camping, ghost-hunting, scuba-diving, ATVing, and a Valentine’s Day skydive – so it makes sense that their engagement was an adventure in itself. Dean planted a fake geocache to surprise Alana while they were on a hike. After reading the cryptic message contained in the cache, she turned around to find Dean on one knee holding a ring. The rest is history.</p>
<p>They will be getting married in an intimate outdoor ceremony at Alana's parents' house on September 12, 2015. They hope to see you there.</p>


<h1>Wedding Party</h1>

<style>
    img{
        width:120px;
        height:120px;
    }
</style>

<?php

print '<div class="row" style="margin-top:10px;">';
echo $this->partial('wedding/about/positionPartial.phtml', 
                    array('thumbnailUrl' => '/weddingpics/Alana.png',
                          'position'     => 'Bride',
                          'name'         => 'Alana Thomas'));
echo $this->partial('wedding/about/positionPartial.phtml', 
                    array('thumbnailUrl' => '/weddingpics/Dean.png',
                          'position'     => 'Groom',
                          'name'         => 'Dean Clow'));
print '</div>';
print '<div class="row" style="margin-top:30px;">';
echo $this->partial('wedding/about/positionPartial.phtml', 
                    array('thumbnailUrl' => '/weddingpics/Deena.png',
                          'position'     => 'Maid of Honor',
                          'name'         => 'Danielle Barnard'));
echo $this->partial('wedding/about/positionPartial.phtml', 
                    array('thumbnailUrl' => '/weddingpics/Trisatn.png',
                          'position'     => 'Best Man',
                          'name'         => 'Tristan Clow'));
print '</div>';
print '<div class="row" style="margin-top:10px;">';
echo $this->partial('wedding/about/positionPartial.phtml', 
                    array('thumbnailUrl' => '/weddingpics/Dylan.png',
                          'position'     => 'Bridesman',
                          'name'         => 'Dylan Thomas'));
echo $this->partial('wedding/about/positionPartial.phtml', 
                    array('thumbnailUrl' => '/weddingpics/Stephanie.png',
                          'position'     => 'Groomsmaid',
                          'name'         => 'Stephanie Loots'));
print '</div>';
?>

<div class="row" style="margin-top:30px;">
    <div class="col-sm-6 col-md-6 col-md-offset-3">
        <div class="col-sm-5 col-md-5"><img src="/weddingpics/Cameron.png" alt="Cameron Naish" title="Cameron Naish" /></div>
        <div class="col-sm-7 col-md-7 positionSpacing"><strong>Officiant</strong><br />Cameron Naish</div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#aboutNav").attr("class", "active"); 
    }, 0);
});
</script>

<style>
    .positionSpacing{
        margin-left:-55px;
    }
    @media only screen 
    and (min-device-width : 768px) 
    and (max-device-width : 1024px) {
        .positionSpacing{
            margin-left:-10px;
        }
    }
</style>