<div class="col-sm-6 col-md-6">
    <div class="col-sm-5 col-md-5"><img src="<?php print $this->thumbnailUrl; ?>" alt="<?php print $this->name; ?>" title="<?php print $this->name; ?>" /></div>
    <div class="col-sm-7 col-md-7 positionSpacing" style="font-family:Trebuchet MS;"><strong><?php print $this->position; ?></strong><br /><span style="font-family:Georgia;"><?php print $this->name; ?></span></div>
</div>