<!DOCTYPE html>
<html lang="en">
    <head>
        <title>deanclow.com</title>
        <meta name="keywords" content="" />
		<meta name="description" content="" />
<!-- 
Urbanic Template 
http://www.templatemo.com/preview/templatemo_395_urbanic 
-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--<link rel="shortcut icon" href="PUT YOUR FAVICON HERE">-->
        
        <!-- Google Web Font Embed -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
        
        <!-- Bootstrap core CSS -->
        <link href="/template/css/bootstrap.css" rel='stylesheet' type='text/css'>

        <!-- Custom styles for this template -->
        <link href="/template/js/colorbox/colorbox.css"  rel='stylesheet' type='text/css'>
        <link href="/template/css/templatemo_style.css"  rel='stylesheet' type='text/css'>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        
        <script src="/template/js/jquery.min.js" type="text/javascript"></script>
        <script src="/template/js/bootstrap.min.js"  type="text/javascript"></script>
        <script src="/template/js/stickUp.min.js"  type="text/javascript"></script>
        <script src="/template/js/colorbox/jquery.colorbox-min.js"  type="text/javascript"></script>
        <script src="/template/js/templatemo_script.js"  type="text/javascript"></script>
    </head>
    
    <body>

        <div class="templatemo-top-bar" id="templatemo-top" style="padding-bottom:12px;">
            <div class="container">
                <div class="subheader">
                    <div id="email" class="pull-right">
                            <img src="/template/images/email.png" alt="email"/>
                            <a href="mailto:deanrclow@gmail.com" style="color:#e67e22">deanrclow@gmail.com</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-green" href="#" role="button">Log in</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="templatemo-top-menu">
            <div class="container">
                <!-- Static navbar -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                </button>
                        </div>
                        <div class="navbar-collapse collapse" id="templatemo-nav-bar">
                            <ul class="nav navbar-nav navbar-right" style="margin-top: 40px;">
                                <li id="homeNav"><a onclick="window.location.href='/';" href="#">HOME</a></li>
                                <li id="aboutNav"><a onclick="window.location.href='/about';" href="#">ABOUT</a></li>
                                <li id="resumeNav"><a onclick="window.location.href='/resume';" href="#">RESUME</a></li>
                                <li id="blogNav"><a onclick="window.location.href='/blog-post/index';" href="#">BLOG</a></li>
                                <li id="chessNav"><a onclick="window.location.href='/chessgames/index';" href="#">CHESS</a></li>
                                <li id="contactNav"><a onclick="window.location.href='/contact/index';" href="#">CONTACT</a></li>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div><!--/.container-fluid -->
                </div><!--/.navbar -->
            </div> <!-- /container -->
        </div>
        
        <div id="templatemo-contact">
            <div class="container">
                <div class="row" style="margin-top:20px;">
                    <?php echo $this->layout()->content ?>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- #templatemo-contact -->

        <div class="templatemo-footer" >
            <div class="container">
                <div class="row">
                    <div class="text-center">

                        <div class="footer_container">
                            <ul class="list-inline">
                                <li>
                                    <a href="https://www.facebook.com/dean.clow.94">
                                        <span class="social-icon-fb"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="social-icon-linkedin"></span>
                                    </a>
                                </li>
                            </ul>
                            <div class="height30"></div>
                            <a class="btn btn-lg btn-orange" href="#" role="button" id="btn-back-to-top">Back To Top</a>
                            <div class="height30"></div>
                        </div>
                        <div class="footer_bottom_content">
                        	Copyright © <?php print date("Y"); ?> <a href="http://deanclow.com">deanclow.com</a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
<!-- templatemo 395 urbanic -->
<!-- 
    Free HTML5 Templates
    http://www.templatemo.com
-->
    </body>
</html>