<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/ckfinder/ckfinder.js"></script>
<form method="post" enctype="multipart/form-data">
    <fieldset>
        <input type="hidden" name="submitted" value="1" />
        <div class="row">
            <label for="title">Title</label> <input type="text" name="title" id="title" value="<?php print $this->model->getTitle(); ?>" />
        </div>
        <div class="row">
            <label for="body">Body</label> <textarea name="body" id="body"><?php print $this->model->getBody(); ?>"</textarea>
            <script>
            //CKEDITOR.replace( 'body' );
            var editor = CKEDITOR.replace( 'body' );
            CKFinder.setupCKEditor( editor, '../' ) ;
            </script>
        </div>
        <div class="row">
            <label for="shortbody">Short Body</label> <input type="text" name="shortbody" id="shortbody" value="<?php print $this->model->getBriefBody(); ?>" />
        </div>
        <div class="row">
            <label for="titleimage">Title Image</label> <input type="text" name="titleimage" id="titleimage" value="<?php print $this->model->getTitleImage(); ?>" />
        </div>
        <div class="row">
            <input type="submit" value="Submit" />
        </div>
    </fieldset>
</form>