<div class="blog_box">
    <?php
    
    $count = 1;
    foreach($this->posts as $post){
        print  '<div class="col-sm-5 col-md-6 blog_post">
                    <ul class="list-inline">
                        <li class="col-md-4">
                            <a href="#">
                                <img class="img-responsive" src="'.$post->getTitleImage().'" alt="gallery 1" />
                            </a>
                        </li>
                        <li  class="col-md-8">
                            <div class="pull-left">
                                <span class="blog_header">'.$post->getTitle().'</span><br/>
                                <span>
                                    <img style="width:12px;height:12px;" src="/img/thumbs_up.ico" /> '.$post->getUpVotes().'
                                    &nbsp;&nbsp;<img style="width:12px;height:12px;" src="/img/thumbs_down.ico" /> '.$post->getDownVotes().'
                                </span>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-orange" href="/blog-post/show/'.$post->getId().'" role="button">'.$post->getDate().'</a>
                            </div>
                            <div class="clearfix"> </div>
                            <p class="blog_text">
                                '.$post->getBriefBody().'...
                            </p>
                        </li>
                    </ul>
                </div> <!-- /.blog_post 1 -->';
        if($count%2==0){
            print '<div class="templatemo_clear"></div>';
        }
        $count++;
    }
            
    ?>
</div>

<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function(){
       $(".nav li").attr("class", "");  
       $("#blogNav").attr("class", "active"); 
    }, 0);
});
</script>