<!DOCTYPE html>
<html lang="en">
    <head>
        <title>The wedding of Alana &amp; Dean</title>
        <meta name="keywords" content="" />
		<meta name="description" content="" />
<!-- 
Urbanic Template 
http://www.templatemo.com/preview/templatemo_395_urbanic 
-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--<link rel="shortcut icon" href="PUT YOUR FAVICON HERE">-->
        
        <!-- Google Web Font Embed -->
        <link href='/template/css/googlefont.css' rel='stylesheet' type='text/css'>
        
        <!-- Bootstrap core CSS -->
        <link href="/template/css/bootstrap.css" rel='stylesheet' type='text/css'>

        <!-- Custom styles for this template -->
        <link href="/template/js/colorbox/colorbox.css"  rel='stylesheet' type='text/css'>
        <link href="/template/css/templatemo_style.css"  rel='stylesheet' type='text/css'>

        <script src="/js/jquery.min.js" type="text/javascript"></script>
        <script src="/js/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/js/jquery.ui.touch.js" type="text/javascript"></script>
        <script src="/js/bootstrap.min.js"  type="text/javascript"></script>
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    
    <body>

        <div class="templatemo-top-menu" style="min-height:50px;">
            <div class="container">
                <!-- Static navbar -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <div class="navbar-collapse collapse" id="templatemo-nav-bar">
                            <ul class="nav navbar-nav navbar-right" style="margin-top: 5px;">
                                <?php
                                $hasIdentity = $this->identityHelper();
                                if($hasIdentity){
                                    print <<<HTML
<li class="active" id="homeNav"><a onclick="window.location.href='/wedding';" href="#">HOME</a></li>
<li id="rsvpNav"><a onclick="window.location.href='/rsvp';" href="#">RSVP</a></li>
<li><a href="/weddinguser/logout">LOG OUT</a></li>
HTML;
                                }else{
                                    print <<<HTML
<li class="active" id="homeNav"><a onclick="window.location.href='/wedding';" href="#">HOME</a></li>
<li id="aboutNav"><a onclick="window.location.href='/weddingabout';" href="#">ABOUT</a></li>
<li id="rsvpNav"><a onclick="window.location.href='/rsvp/rsvp';" href="#">RSVP</a></li>
<li id="registryNav"><a onclick="window.location.href='/registry';" href="#">REGISTRY</a></li>
<li id="contactNav"><a onclick="window.location.href='/weddingcontact';" href="#">CONTACT</a></li>
<li><a href="/weddinguser/login">LOG IN</a></li>
HTML;
                                }
                                ?>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div><!--/.container-fluid -->
                </div><!--/.navbar -->
            </div> <!-- /container -->
        </div>

        <div id="templatemo-contact">
            <div class="container">
                <div class="row" style="margin-top:20px;">
                    <?php echo $this->layout()->content ?>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- #templatemo-contact -->
        
        <div class="templatemo-footer" >
            <div class="container">
                <div class="row">
                    <div class="text-center">
                        <div class="height30"></div>
                        <div class="footer_bottom_content">
                        	Copyright © <?php print date("Y"); ?> <a href="http://deanclow.com">deanclow.com</a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

<!-- 222 / 206 templateemo_style.css -->

<style>
    .navbar-default .navbar-nav > li > a:focus {
        background-color: #738965;
        color:#fff;
    }
    .navbar-default .navbar-nav > .active > a,
    .navbar-default .navbar-nav > .active > a:hover,
    .navbar-default .navbar-nav > .active > a:focus {
        background-color: #738965;
    }
    .navbar-default .navbar-nav > li > a:hover,
    .navbar-default .navbar-nav > li > a:focus {
        background-color: #738965;
    }
    h1, h2, h3, h4, h5, h6, span, p {
        font-family:Georgia;
    }
</style>